### PR TITLE
15 get current version

### PR DESCRIPTION
**Pull request by coordt**
**Changes bump-my-version into subcommands**

- Is backward-compatible with previous versions
- `bump-my-version` forwards command to `bump-my-version bump` subcommand
- Only problem is that Click will not show help automatically. It must provide `--help`

**Added show subcommand.**
- supersedes the `--list` option
- provides much more capability
- Can output in YAML, JSON, and default
- Can specify one or more items to display
- Can use dotted notation to pull items from nested data structures.

### CODE REVIEW

**Comment by kdeldycke** [comment]
First observation playing with this PR: there is no way to get the help screen of subcommands. But that's not important right now, as `bump-my-version` is still `v0.x`. Can be addressed in the future.

So for each variation of the `--help` invokation:
```shell-session
$ bump-my-version --help
$ bump-my-version --help bump
$ bump-my-version --help show
$ bump-my-version bump --help
$ bump-my-version bump --help
```

I get the same help screen:
```shell-session                                                                                                                                                                                                                    
 Usage: bump-my-version [OPTIONS] COMMAND [ARGS]...                                                                                                                                                                 
                                                                                                                                                                                                                    
 Version bump your Python project.                                                                                                                                                                                  
                                                                                                                                                                                                                    
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --version      Show the version and exit.                                                                                                                                                                        │
│ --help         Show this message and exit.                                                                                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ bump                     Change the version.                                                                                                                                                                     │
│ show                     Show current configuration information.                                                                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I guess that is something pertaining to the way `Click` is structured, with the `--help` option being eager.

**Comment by kdeldycke** [comment]
Unimportant nitpick: maybe you can bump the version in this branch to `v0.6.0-dev` or something, just to make sure my test investigations are not using the stable version.

So I can see something other than `0.5.1` in the output:
```shell-session
$ bump-my-version bump --dry-run --verbose patch
Starting BumpVersion 0.5.1                                                                                                                                                                                          
(...)
```

**Comment by kdeldycke** [comment]
BTW, the latest command I refered to doesn't work:

```shell-session
$ bump-my-version bump --dry-run --verbose patch
Starting BumpVersion 0.5.1                                                                                                                                                                                          
Reading config file pyproject.toml:                                                                                                                                                                                 
Specified version (2.17.4) does not match last tagged version (2.17.3)                                                                                                                                              
                                                                                                                                                                                                                    
 Usage: bump-my-version bump [OPTIONS] [ARGS]...                                                                                                                                                                    
                                                                                                                                                                                                                    
 Try 'bump-my-version bump --help' for help.                                                                                                                                                                        
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Unknown version part: bump                                                                                                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                                                                                                                                                                                                                    
```

Where:
```shell-session
$ cat ./pyproject.toml
```
```toml
[tool.bumpversion]
current_version = "2.17.4"
allow_dirty = true

[[tool.bumpversion.files]]
filename = "./changelog.md"
search = "[{current_version} (unreleased)]("
replace = "[{new_version} (unreleased)]("
```

And:
```shell-session
$ head ./changelog.md
```
```md
# Changelog

## [2.17.4 (unreleased)](https://github.com/kdeldycke/workflows/compare/v2.17.3...main)

- Testing bump-my-version `v0.6.0-dev`.
```

**Comment by kdeldycke** [comment]
On a positive note, the CLI to fetch the current version works great and properly separate `<stdout>` and `<stderr>` outputs:
```shell-session
$ bump-my-version show current_version
Specified version (2.17.4) does not match last tagged version (2.17.3)
2.17.4

$ bump-my-version show current_version > current.txt
Specified version (2.17.4) does not match last tagged version (2.17.3)

$ cat ./current.txt
2.17.4
```

So I'm happy because we'll be able to close #15 soon! :)

**Comment by kdeldycke** [comment]
BTW, if you need inspiration for implementing subcommands with Click for big and complicated CLIs, feel free to look at the source code of my biggest project `mpm`: https://github.com/kdeldycke/meta-package-manager/blob/main/meta_package_manager/cli.py#L265

Click can be frustrating some times so you're not alone in this journey! 🤗

**Comment by kdeldycke** [comment]
If you want to check my integration branch of the upcoming bump-my-version 0.6.0, here it is: https://github.com/kdeldycke/workflows/pull/591/files

**Comment by coordt** [comment]
@kdeldycke 

The `--help` issue should be better in 0.5.1dev6

The `bump` subcommand should work normally.

Also changed this version to 0.5.1dev6

**Comment by kdeldycke** [comment]
Thanks @coordt for the latest updates.

I can confirm that this PR solves #15, and I couldn't find any regressions compared to the way I was previously using bump-my-version for.

This PR LGTM, and can be merged upstream and published as a new version.

**Comment by kdeldycke** [comment]
Thanks @coordt for the merge and the new 0.6.0 release!

**Pull request merged**
