### PR TITLE
Fix legacy multiline

### PR DESCRIPTION
**Pull request by coordt**
We discovered that commas in legacy multiline options are replaced by newline which produced errors on configurations for bump2version.

Debug lead me to autocast which doesn't expect strings with both commas and newlines.

### CODE REVIEW

**Comment by coordt** [comment]
@ziima Just a warning, I will be removing the legacy stuff soon for version 1.0

**Comment by ziima** [comment]
How soon is soon?

**Comment by coordt** [comment]
Within a month, probably. I'm hoping to get it nearly there next week, since I have some time off.

Is there anything keeping you from switching to TOML (other than you have plenty of other things to do :) )?

**Comment by ziima** [comment]
We have quite a number of projects and we tend to upgrade project configuration only with major or minor releases. So I'd prefer longer period to transition all the projects' configuration while keeping an option to just do a patch without the need to upgrade the configuration. I guess I could handle that with `<1` version of bump-my-version for some time.

Generally speaking, I'd suggest to keep the ability to read the INI configuration for some time, despite all the problems. I guess there's a number of projects which use `bump2version` or `bumpversion` and the configuration is basically part of its API. I believe keeping the compatibility would help users in transition to `bump-my-version`.

**Comment by coordt** [comment]
An idea I was throwing around in my head was to provide various hooks for plugins via [Pluggy](https://pluggy.readthedocs.io/en/stable/).

One of the hooks I could provide is for configuration reading. That would allow me to move "legacy" stuff to plugins.

What do you think?

**Comment by ziima** [comment]
OK, that seems reasonable. Plugins may be tricky though.

**Pull request merged**
