### PR TITLE
feat: add Docker image to run without installation

### PR DESCRIPTION
**Pull request by reneleonhardt**
* add Docker image to run without installation
* add shortcuts for docker run (stdout only)
* let Dependabot update docker, pip, GitHub Actions

In order to allow more integration scenarios we allow bumping to stdout only without changing files.

```shell
CURRENT_VERSION=1.2.3
NEW_VERSION=$(docker run --rm bump-my-version patch $CURRENT_VERSION)
```

### CODE REVIEW

**Comment by coordt** [comment]
@reneleonhardt I like the docker work you've done, but I don't understand the additional CLI commands.

In any case, there are several things that I need before I can merge this:

1. Line 22 in the Dockerfile needs updating when bump-my-version updates. Can you modify the pyproject.toml to update this?
2. Can you provide some documentation, or even some notes if English isn't your native language, that describes how you see this working?

**Comment by reneleonhardt** [comment]
> @reneleonhardt I like the docker work you've done, but I don't understand the additional CLI commands.

The CLI commands were kind of natural for me: In CI workflows I just need a tool to bump a version, usually at patch level.
I couldn't use the existing commands without a configuration file, so I created new commands to just do input/output: Convert a version string to a new version without reading or writing files.

> In any case, there are several things that I need before I can merge this:
> 
>     1. Line 22 in the Dockerfile needs updating when bump-my-version updates. Can you modify the pyproject.toml to update this?

I couldn't know if you were gonna accept these changes, so I didn't put in the extra work of integrating this example beautifully.
If you would accept it, I would replace those Dockerfile directives with https://github.com/docker/metadata-action to add all labels automatically during the release workflow, including the version number from git.
When everything is working I could add flags to read `--current-version` from .git to make it even easier to integrate it into CI workflows.

>     2. Can you provide some documentation, or even some notes if English isn't your native language, that describes how you see this working?

I added some examples, do you have access to https://hub.docker.com/u/calloway?
Please checkout this branch locally, build the docker image without pushing it and test the examples yourself.
`docker build -t calloway/bump-my-version:latest .`

**Comment by coordt** [comment]
Based on what you've said, would it be easier to allow more arguments to the `show` command?

It seems like a misstep on my part to forget the non-config-file use case.

**Comment by reneleonhardt** [comment]
I wouldn't call it a misstep, maybe an oversight 😅
As far as I understand the show command is not the main purpose, this project is able to do so much more.
I just tried to see it from the user's perspective, my simplest use case was "I know the current_version and what kind of next version I want"... so I thought calling `patch 1.2.3` would be the most intuitive command line... instead of `show new_version --increment patch --current-version 1.2.3` 😄

**Comment by reneleonhardt** [comment]
@coordt It would've been nice to hear a reasoning for closing my work without comment.

**Comment by mkresse** [comment]
Since this PR is closed, is there any replacement for a provided docker image planned? This would be really helpful in order to use bump-my-version in CI without installation.

**Pull request closed without merging**
